### ISSUE TITLE
Error with docker image 

### ISSUE THREAD

**Issue by tolstihin** [khezen/docker-elasticsearch#19]
Hi, I have error with version 5, docker container exit with code 1

**Comment by pgbezerra** [comment]
Could you copy your ``docker-compose.yml`` or your ``docker run`` command?

**Comment by tolstihin** [comment]
```
version: '3'

services:

  elasticsearch:
    restart: always
    image: khezen/elasticsearch:5.3
    environment:
         LOG_LEVEL: INFO
         CLUSTER_NAME: elasticsearch
         MINIMUM_MASTER_NODES: 1
         HOSTS: 127.0.0.1
         NODE_NAME: node-1
         NODE_MASTER: 'true'
         NODE_DATA: 'true'
         NODE_INGEST: 'true'
         HEAP_SIZE: 512m
         ELASTIC_PWD: password
         KIBANA_PWD: password
         HTTP_SSL: 'true'
    ports:
      - 9200:9200
    volumes:
      - /srv/docker/elastic/data:/usr/share/elasticsearch/data
      - /srv/docker/elastic/elasticsearch:/usr/share/elasticsearch/config
```
