### ISSUE TITLE
ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")

### ISSUE THREAD

**Issue by mark-monserrat** [khezen/docker-elasticsearch#29]
ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")

But I already created a PR for this issue... see #28

**Comment by khezen** [comment]
I am unable to reproduce the issue with the following test:

`docker-compose up`

here is my `docker-compose.yml`
```
version: '2'
services:
    elasticsearch:
        image: khezen/elasticsearch
        environment:
            ELASTIC_PWD: changeme
            KIBANA_PWD: changeme
            TS_PWD: changeme
        volumes:
            - es_data:/elasticsearch/data
            - es_config:/elasticsearch/config
        ports:
             - "9200:9200"
             - "9300:9300"
        networks:
            - elk
        restart: always

    kibana:
        links:
            - elasticsearch
        image: khezen/kibana
        environment:
            KIBANA_PWD: changeme
            ELASTICSEARCH_HOST: elasticsearch
            ELASTICSEARCH_PORT: 9200
        volumes:
            - kibana_config:/opt/kibana-6.0.0-linux-x86_64/config
            - es_config:/etc/elasticsearch
        ports:
             - "5601:5601"
        networks:
            - elk
        restart: always

volumes:
  es_config:
    driver: local
  es_data:
    driver: local
  kibana_config:
    driver: local

networks:
  elk:
    driver: bridge
```

If you tell me how you run elasticsearch I may be able to help you.
