### ISSUE TITLE
Multi Node on GCE

### ISSUE THREAD

**Issue by romankor** [khezen/docker-elasticsearch#33]
Hi,
It might be that i don't understand something how TLS should work in general.

I am setting up a production cluster on dockers in GCE (google cloud) with the gce discovery plugin. Every node on the startup generates all he certificates. So no node would connect with another failing on SSL and unknown_certificate exception.
I did resolve that issue where I am generating all the certificates in the docker image which is stored than i our private google container repository. So the node comes up and does not have to generate anything.
The question here is did i misunderstood something about security and the means how searchguard should work in general ? 

I also think there is bug in the issue-31.yml thats a snippet from it.

``` yml
    es-data:
        build: ../
        environment:
          SYSCTL_KEY: vm.max_map_count
          SYSCTL_VALUE: '262144'
          HEAP_SIZE: 1g
          CLUSTER_NAME: condor-es
          HOSTS: es-master
          NODE_DATA: 'true'
          NODE_INGEST: 'false'
          NODE_MASTER: 'false'
          NODE_NAME: ''
          ELASTIC_PWD: changeme
          KIBANA_PWD: changeme
          LOGSTASH_PWD: changeme
          BEATS_PWD: changeme
          CA_PWD: changeme
          TS_PWD: changeme
          KS_PWD: changeme
          HOSTS: 0.0.0.0, [::3]
```

`HOSTS` is repeated twice and last value overrides the actual `es-master` so i ran that example and didnt see that the nodes actually connect with each other.

EDIT: 

I actually improved that a little bit. 
I removed the node certificate generation from the `gen_all.sh` which is run inside the Dockerfile , and the node certificate generation running it on the node startup. The node are able to communicate with each other and each node has a different certificate
