### ISSUE TITLE
Logstash unauthorized to connect to elasticsearch

### ISSUE THREAD

**Issue by ChaDup** [khezen/docker-elasticsearch#34]
Hi, 

I have successfully installed elasticsearch and kibana with searchguard. 

I am now trying to add logstash, and I get unauthorized-401 error. 

Here is my output config of my logstash.conf file : 

```
output {
   elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "waziup_all_sensors-%{+YYYY.MM.dd}"
      user => logstash
      password => logstash
      ssl => true
      ssl_certificate_verification => false
      truststore => "/var/docker/es_config/searchguard/ssl/truststore.jks"
      truststore_password => pass
   }
```

I have set ssl certificate verification to false, otherwise it says that it is not the correct host set into the certificate (elasticsearch). But with localhost I get connection refused. 

Here is my docker-compose.yml file : 

```
version: '2'
services:
    elasticsearch:
        image: khezen/elasticsearch
        environment:
            ELASTIC_PWD: ***
            KIBANA_PWD: ***
            TS_PWD: pass
        volumes:
            - /var/docker/es_data:/elasticsearch/data
            - /var/docker/es_config:/elasticsearch/config
        ports:
             - "9200:9200"
             - "9300:9300"
        networks:
            - elk
        restart: always

    kibana:
        links:
            - elasticsearch
        image: khezen/kibana
        environment:
            KIBANA_PWD: ***
            ELASTICSEARCH_HOST: elasticsearch
            ELASTICSEARCH_PORT: 9200
        volumes:
            - /var/docker/kibana_config:/opt/kibana-6.1.1-linux-x86_64/config
            - /var/docker/es_config:/etc/elasticsearch
        ports:
             - "5601:5601"
        networks:
            - elk
        restart: always

    logstash:
        links:
            - elasticsearch
        image: docker.elastic.co/logstash/logstash-oss:6.1.2
        environment:
            LOGSTASH_PWD: logstash
            TS_PWD: pass
            ELASTICSEARCH_HOST: elasticsearch
            ELASTICSEARCH_PORT: 9200
        volumes:
            - /var/docker/logstash_pipeline:/usr/share/logstash/pipeline
            - /var/docker/es_config:/var/docker/es_config
        ports:
            - "55555:55555"
        networks:
            - elk
        restart: always

networks:
elk:
        driver: bridge
```

And here is the error : 

```
logstash_1`       | [2018-01-25T09:54:04,604][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://logstash:xxxxxx@elasticsearch:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError, :error=>"Got response code '401' contacting Elasticsearch at URL 'https://elasticsearch:9200/'"}
```

Any help ? 

Thanks

**Comment by khezen** [comment]
How about that?
```
version: '2'
services:
    elasticsearch:
        image: khezen/elasticsearch
        environment:
            ELASTIC_PWD: ***
            KIBANA_PWD: ***
            LOGSTASH_PWD: logstash
            TS_PWD: pass
        volumes:
            - /var/docker/es_data:/elasticsearch/data
            - /var/docker/es_config:/elasticsearch/config
        ports:
             - "9200:9200"
             - "9300:9300"
        networks:
            - elk
        restart: always

    kibana:
        links:
            - elasticsearch
        image: khezen/kibana
        environment:
            KIBANA_PWD: ***
            ELASTICSEARCH_HOST: elasticsearch
            ELASTICSEARCH_PORT: 9200
        volumes:
            - /var/docker/kibana_config:/opt/kibana-6.1.1-linux-x86_64/config
            - /var/docker/es_config:/etc/elasticsearch
        ports:
             - "5601:5601"
        networks:
            - elk
        restart: always

    logstash:
        links:
            - elasticsearch
        image: docker.elastic.co/logstash/logstash-oss:6.1.2
        environment:
            LOGSTASH_PWD: logstash
            TS_PWD: pass
            ELASTICSEARCH_HOST: elasticsearch
            ELASTICSEARCH_PORT: 9200
        volumes:
            - /var/docker/logstash_pipeline:/usr/share/logstash/pipeline
            - /var/docker/es_config:/var/docker/es_config
        ports:
            - "55555:55555"
        networks:
            - elk
        restart: always

networks:
elk:
        driver: bridge
```
