### ISSUE TITLE
HTTP_SSL: "false" -> Stalling for Elasticsearch...

### ISSUE THREAD

**Issue by emepetres** [khezen/docker-elasticsearch#40]
Hi,

Using here tag `5` and docker-compose. If I set `HTTP_SSL: "false"` in the yaml file, I get `Stalling for Elasticsearch...` forever. If I remove `HTTP_SSL` env variable from the file, it works as expected.

This is the docker compose file to reproduce the error:
```
version: '3'
services:
    elasticsearch:
        container_name: elastic
        image: khezen/elasticsearch:5
        environment:
            ELASTIC_PWD: changeme
            KIBANA_PWD: changeme
            HEAP_SIZE: 1g
            LOG_LEVEL: DEBUG
            HTTP_SSL: "false"
        volumes:
            - ./es/data:/elasticsearch/data
            - ./es/config:/elasticsearch/config
        ports:
             - "9200:9200"
             - "9300:9300"
        network_mode: bridge
        restart: always
```
