### ISSUE TITLE
jvm.options file missing on the config folder after build

### ISSUE THREAD

**Issue by souparvo** [khezen/docker-elasticsearch#46]
After cloning the repo from the master branch:

`[root@host docker]# git clone https://github.com/khezen/docker-elasticsearch.git`

Then running copying the _docker-compose.yml_ file to the the command on the repo folder using the default _docker-compose.yml_ but with your image khezen/elasticsearch:6.5.4 

`[root@host docker-elasticsearch]#  cp examples/docker-compose.yml .`

I made the following alterations to the _docker-compose.yml_ file:

```
version: '2'
services:
    es-master:
        build: .
        environment:
            NODE_NAME: master
            ELASTIC_PWD: changeme
            KIBANA_PWD: changeme
            CLUSTER_NAME: es-sg-cluster
            #HTTP_SSl: 'false'
        volumes:
            - /data/elasticsearch:/elasticsearch/data
            - /etc/elasticsearch:/elasticsearch/config
        ports:
             - "9202:9200"
             - "9302:9300"
        network_mode: bridge
        restart: always

```

I stumbled upon an error after the end of the configuration of searchguard. The following error messages were displayed:

> es-master_1  | Stalling for Elasticsearch...
es-master_1  | Exception in thread "main" java.nio.file.NoSuchFileException: /elasticsearch/config/jvm.options
es-master_1  | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
es-master_1  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
es-master_1  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
es-master_1  | 	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
es-master_1  | 	at java.nio.file.Files.newByteChannel(Files.java:361)
es-master_1  | 	at java.nio.file.Files.newByteChannel(Files.java:407)
es-master_1  | 	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
es-master_1  | 	at java.nio.file.Files.newInputStream(Files.java:152)
es-master_1  | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:60)
es-master_1  | Stalling for Elasticsearch...
es-master_1  | Stalling for Elasticsearch...
es-master_1  | Stalling for Elasticsearch...

**SOLUTION:** add the _jvm.options_ to the defined default _/etc/elasticsearch/_ folder where the volume is stored and then rerun the command `docker-compose up`

I guess you are deleting the file somewhere in the process, wich I have not been able to find in the _Dockerfile_.

Thank you.
