### ISSUE TITLE
Optional SSL

### ISSUE THREAD

**Issue by bclermont** [khezen/docker-elasticsearch#8]
Doing https at ES level might not the best the idea, even more with a self signed SSL cert.

I'm running a https://docs.traefik.io/ in front of it. Which do a better job of secure with SSL (using real letsencrypt cert).

There should be an environment variable to not bind https on port 9200.

**Comment by bclermont** [comment]
```
level=warning msg="Error forwarding to https://172.18.0.20:9200, err: x509: certificate is valid for 127.0.0.1, not 172.18.0.20"
```

what I expected, self signed cause problems

**Comment by Khezen** [comment]
#10

**Comment by khezen** [comment]
I've updated 5.3 exposing a new environment variable HTTP_SSL which is boolean.

@bclermont 
I'd be grateful if you were willing to share your traefik setup with me. I am interested in this technology and it would also help to make this image easier to integrate.

**Comment by bclermont** [comment]
```
version: '3.1'

services:
  proxy:
    image: traefik:v1.2.1-alpine
    command: --web --docker --docker.exposedbydefault=false --defaultentrypoints="http,https" --acme=true --acme.storage=/data/acme.json --acme.email=yyy@xxx.com --acme.entrypoint=https --acme.onhostrule=true --acme.ondemand=false --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS' --checknewversion=false
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /data/traefik/:/data/
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    labels:
      traefik.backend: elasticsearch
      traefik.enable: "true"
      traefik.protocol: "http"
      traefik.port: "9200"
      traefik.frontend.rule: "Host:es.xxx.com"
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
```

if `es.xxx.com` resolve to the IP of the host that run traefik, it will create SSL certificate on the fly :)
